// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-crypto-rates.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_crypto_rates_default = defineTool({
  name: "list_crypto_rates",
  title: "List crypto GHS rates",
  description: "List the current SwiftChain X buy/sell rates (in GHS per USD) for each supported cryptocurrency.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("crypto_rates").select("crypto_name, crypto_symbol, buy_rate, sell_rate, currency");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { rates: data }
    };
  }
});

// src/lib/mcp/tools/list-payment-methods.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_payment_methods_default = defineTool2({
  name: "list_payment_methods",
  title: "List payment methods",
  description: "List the active SwiftChain X payment methods (Mobile Money, bank, etc.) customers can pay with.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("payment_methods").select("label, type, details, instructions").eq("active", true).order("sort_order");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { methods: data }
    };
  }
});

// src/lib/mcp/tools/get-my-trades.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var get_my_trades_default = defineTool3({
  name: "get_my_trades",
  title: "Get my trades",
  description: "Return the signed-in SwiftChain X customer's own trades (orders), most recent first.",
  inputSchema: {
    limit: z.number().int().positive().describe("Maximum number of trades to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("trades").select("id, trade_type, action, item, amount, status, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { trades: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hskhwejndtjcypfhppey";
var mcp_default = defineMcp({
  name: "swiftchain-x-mcp",
  title: "SwiftChain X",
  version: "0.1.0",
  instructions: "Tools for SwiftChain X \u2014 Ghana's crypto & gift-card trading desk. Use `list_crypto_rates` and `list_payment_methods` for public rate/payment info, and `get_my_trades` to read the signed-in customer's own orders.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_crypto_rates_default, list_payment_methods_default, get_my_trades_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
